// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29.11.2025, 13:05:39
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/isuus/isuus/forestproject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/plugins/**/*.{js,ts,mjs}","E:/isuus/isuus/forestproject/composables/**/*.{js,ts,mjs}","E:/isuus/isuus/forestproject/utils/**/*.{js,ts,mjs}","E:/isuus/isuus/forestproject/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/isuus/isuus/forestproject/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;