// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29.11.2025, 16:09:06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/km929/Desktop/urbathbib/forestproject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/plugins/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/urbathbib/forestproject/composables/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/urbathbib/forestproject/utils/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/urbathbib/forestproject/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/urbathbib/forestproject/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;